import 'artist_lick_model.dart';

/// 유명 기타리스트 4대 거장 시그니처 릭 프리셋 라이브러리
final List<ArtistLick> kArtistLickPresets = [
  // ==========================================
  // 1. Jimi Hendrix (지미 헨드릭스)
  // ==========================================
  const ArtistLick(
    id: 'hendrix_little_wing',
    artist: 'Jimi Hendrix',
    title: 'Little Wing Chord-Melody Fill',
    difficulty: 'Intermediate',
    defaultKey: 'G Major',
    targetChord: 'G',
    applicableDegrees: ['I', 'IV'],
    scaleUsed: 'G Major Pentatonic + 6th',
    cagedForm: 'E Form',
    pentatonicBox: 1,
    description: '왼손 엄지로 베이스를 감싸 쥔 채, 4도/5도 더블스탑과 해머링을 섞어 코드를 노래하듯 장식하는 헨드릭스식 R&B 발라드 시그니처 릭입니다.',
    theoryTips: 'G코드의 루트(G)와 4도(C)를 동시에 탄현한 뒤 5도(D)로 해머링하여 화성적 텐션(Suspended)을 해결합니다. 마지막 6도(E)와 5도(D) 장식음이 특유의 소울풀한 여운을 남깁니다.',
    tags: ['Double Stop', 'R&B / Soul', 'Hammer-on', 'Ballad'],
    notes: [
      LickNote(string: 4, fret: 5, duration: 0.5, interval: 'R', noteName: 'G', isTargetNote: true),
      LickNote(string: 3, fret: 5, duration: 0.25, interval: '4', noteName: 'C', technique: NoteTechnique.hammer),
      LickNote(string: 3, fret: 7, duration: 0.5, interval: '5', noteName: 'D', isTargetNote: true),
      LickNote(string: 2, fret: 3, duration: 0.25, interval: '5', noteName: 'D'),
      LickNote(string: 2, fret: 5, duration: 0.5, interval: '6', noteName: 'E', technique: NoteTechnique.pull),
      LickNote(string: 2, fret: 3, duration: 0.5, interval: '5', noteName: 'D', isTargetNote: true),
    ],
  ),

  const ArtistLick(
    id: 'hendrix_castles',
    artist: 'Jimi Hendrix',
    title: 'Castles Made of Sand R&B Fill',
    difficulty: 'Intermediate',
    defaultKey: 'G Major',
    targetChord: 'G',
    applicableDegrees: ['I', 'IV', 'V'],
    scaleUsed: 'G Major Pentatonic (Add 9)',
    cagedForm: 'E Form',
    pentatonicBox: 1,
    description: '맑고 영롱한 클린 톤으로 3도, 5도, 6도, 9도를 넘나들며 아르페지오와 멜로디를 하나로 융합한 릭입니다.',
    theoryTips: '코드톤인 장3도(B)에서 슬라이드로 진입하여 5도(D), 6도(E), 9도(A)를 거쳐 1번줄 루트(G)로 유려하게 안착합니다.',
    tags: ['Slide', 'Major Pentatonic', 'Arpeggio Fill'],
    notes: [
      LickNote(string: 3, fret: 4, duration: 0.25, interval: '3', noteName: 'B', technique: NoteTechnique.slide),
      LickNote(string: 2, fret: 3, duration: 0.25, interval: '5', noteName: 'D'),
      LickNote(string: 2, fret: 5, duration: 0.5, interval: '6', noteName: 'E', technique: NoteTechnique.vibrato),
      LickNote(string: 1, fret: 5, duration: 0.25, interval: '9', noteName: 'A'),
      LickNote(string: 1, fret: 3, duration: 0.75, interval: 'R', noteName: 'G', isTargetNote: true),
    ],
  ),

  const ArtistLick(
    id: 'hendrix_voodoo',
    artist: 'Jimi Hendrix',
    title: 'Voodoo Child Blues Screamer',
    difficulty: 'Advanced',
    defaultKey: 'E Minor',
    targetChord: 'E7',
    applicableDegrees: ['I', 'i'],
    scaleUsed: 'E Minor Blues Scale',
    cagedForm: 'E Form',
    pentatonicBox: 1,
    description: '12프렛 하이 포지션에서 폭발적인 벤딩과 b5 블루노트로 상대를 압도하는 전형적인 헤비 일렉트릭 블루스 릭입니다.',
    theoryTips: '단7도(D)를 1온음 풀벤딩하여 루트(E)에 도달한 뒤, 블루노트(Bb, b5)를 살짝 짚고 4도(A)를 거쳐 루트로 묵직하게 귀환합니다.',
    tags: ['Blues Scale', 'Full Bend', 'Blue Note (b5)', 'Heavy Blues'],
    notes: [
      LickNote(string: 2, fret: 15, duration: 0.5, interval: 'b7', noteName: 'D', technique: NoteTechnique.bendFull),
      LickNote(string: 1, fret: 12, duration: 0.25, interval: 'R', noteName: 'E', isTargetNote: true),
      LickNote(string: 2, fret: 15, duration: 0.5, interval: 'b7', noteName: 'D', technique: NoteTechnique.bendFull),
      LickNote(string: 3, fret: 15, duration: 0.25, interval: 'b5', noteName: 'Bb', technique: NoteTechnique.pull),
      LickNote(string: 3, fret: 14, duration: 0.25, interval: '4', noteName: 'A'),
      LickNote(string: 3, fret: 12, duration: 0.25, interval: 'b3', noteName: 'G'),
      LickNote(string: 4, fret: 14, duration: 0.75, interval: 'R', noteName: 'E', isTargetNote: true),
    ],
  ),

  // ==========================================
  // 2. Eric Clapton (에릭 클랩튼)
  // ==========================================
  const ArtistLick(
    id: 'clapton_crossroads',
    artist: 'Eric Clapton',
    title: 'Crossroads Box 1-to-2 Crossover',
    difficulty: 'Intermediate',
    defaultKey: 'A Minor',
    targetChord: 'A7',
    applicableDegrees: ['I', 'i', 'IV'],
    scaleUsed: 'A Minor Pentatonic Box 1 & 2',
    cagedForm: 'E Form / D Form',
    pentatonicBox: 1,
    description: '블루스 록의 바이블 "Crossroads"에서 펜타토닉 1번 박스와 2번 박스를 빠르게 연결하며 날카롭게 치고 빠지는 클랩튼 전매특허 릭입니다.',
    theoryTips: '4도(D) 풀벤딩으로 5도(E)를 치고, 단7도(G) 벤딩으로 루트(A)를 타격한 뒤 하향 런으로 종결하는 정석 프레이징입니다.',
    tags: ['Blues Rock', 'Full Bend', 'Box Crossover'],
    notes: [
      LickNote(string: 3, fret: 7, duration: 0.5, interval: '4', noteName: 'D', technique: NoteTechnique.bendFull),
      LickNote(string: 2, fret: 5, duration: 0.25, interval: '5', noteName: 'E'),
      LickNote(string: 1, fret: 5, duration: 0.5, interval: 'R', noteName: 'A', isTargetNote: true),
      LickNote(string: 2, fret: 8, duration: 0.5, interval: 'b7', noteName: 'G', technique: NoteTechnique.bendFull),
      LickNote(string: 1, fret: 5, duration: 0.25, interval: 'R', noteName: 'A', isTargetNote: true),
      LickNote(string: 2, fret: 8, duration: 0.25, interval: 'b7', noteName: 'G', technique: NoteTechnique.pull),
      LickNote(string: 2, fret: 5, duration: 0.5, interval: '5', noteName: 'E'),
    ],
  ),

  const ArtistLick(
    id: 'clapton_layla',
    artist: 'Eric Clapton',
    title: 'Layla Sweet 3rd Resolution',
    difficulty: 'Intermediate',
    defaultKey: 'D Major',
    targetChord: 'D',
    applicableDegrees: ['I'],
    scaleUsed: 'D Major/Minor Pentatonic Mix',
    cagedForm: 'A Form',
    pentatonicBox: 2,
    description: '블루지한 벤딩으로 긴장감을 조성하다가, 코드의 가장 달콤한 소리인 장3도(F#)로 정확히 착지하여 해결하는 릭입니다.',
    theoryTips: '마이너 펜타토닉의 4도(G)를 살짝 벤딩해 텐션을 만든 후, 5도(A)와 6도(B)를 거쳐 D코드의 코드톤인 장3도(F#)에 도달해 완벽한 안도감을 줍니다.',
    tags: ['Targeting 3rd', 'Sweet Notes', 'Half Bend'],
    notes: [
      LickNote(string: 2, fret: 8, duration: 0.5, interval: '4', noteName: 'G', technique: NoteTechnique.bendHalf),
      LickNote(string: 1, fret: 5, duration: 0.25, interval: '5', noteName: 'A'),
      LickNote(string: 1, fret: 7, duration: 0.25, interval: '6', noteName: 'B'),
      LickNote(string: 1, fret: 5, duration: 0.25, interval: '5', noteName: 'A'),
      LickNote(string: 2, fret: 7, duration: 0.75, interval: '3', noteName: 'F#', isTargetNote: true),
    ],
  ),

  const ArtistLick(
    id: 'clapton_wonderful',
    artist: 'Eric Clapton',
    title: 'Wonderful Tonight Singing Fill',
    difficulty: 'Beginner',
    defaultKey: 'G Major',
    targetChord: 'G',
    applicableDegrees: ['I', 'V'],
    scaleUsed: 'G Major Pentatonic',
    cagedForm: 'C Form',
    pentatonicBox: 2,
    description: '단 세 개의 프렛 안에서 보컬과 대화하듯 부드럽게 노래하는 슬로우핸드 특유의 멜로딕 발라드 필입니다.',
    theoryTips: '5도(D)와 6도(E)를 디딤돌 삼아 루트(G)로 진입한 후, 9도(A)를 풀벤딩했다가 루트(G)로 떨어지는 편안한 메이저 사운드입니다.',
    tags: ['Ballad', 'Vibrato', 'Major Pentatonic', 'Singing Tone'],
    notes: [
      LickNote(string: 3, fret: 7, duration: 0.25, interval: '5', noteName: 'D'),
      LickNote(string: 3, fret: 9, duration: 0.25, interval: '6', noteName: 'E'),
      LickNote(string: 2, fret: 8, duration: 0.5, interval: 'R', noteName: 'G', isTargetNote: true),
      LickNote(string: 2, fret: 10, duration: 0.5, interval: '9', noteName: 'A', technique: NoteTechnique.bendFull),
      LickNote(string: 2, fret: 8, duration: 0.75, interval: 'R', noteName: 'G', technique: NoteTechnique.vibrato, isTargetNote: true),
    ],
  ),

  // ==========================================
  // 3. Stevie Ray Vaughan (스티비 레이 본)
  // ==========================================
  const ArtistLick(
    id: 'srv_pride_and_joy',
    artist: 'Stevie Ray Vaughan',
    title: 'Pride and Joy Texas Shuffler',
    difficulty: 'Advanced',
    defaultKey: 'E Minor',
    targetChord: 'E7',
    applicableDegrees: ['I', 'V'],
    scaleUsed: 'E Blues Scale + Open Strings',
    cagedForm: 'E Form (Open)',
    pentatonicBox: 1,
    description: '오픈 개방현과 펜타토닉 1번 박스를 맹렬한 스윙 셔플로 오가며 에너지를 분출하는 텍사스 블루스의 상징적인 턴어라운드 릭입니다.',
    theoryTips: '개방현 E음과 2번줄 b7(D)을 때린 뒤, 3번줄의 4도(A)를 거칠게 쿼터/하프 벤딩하고 b3(G)을 거쳐 4번줄 루트(E)로 박력있게 착지합니다.',
    tags: ['Texas Shuffle', 'Open Strings', 'Bending', 'Turnaround'],
    notes: [
      LickNote(string: 1, fret: 0, duration: 0.25, interval: 'R', noteName: 'E', isTargetNote: true),
      LickNote(string: 2, fret: 3, duration: 0.25, interval: 'b7', noteName: 'D'),
      LickNote(string: 2, fret: 0, duration: 0.25, interval: '5', noteName: 'B'),
      LickNote(string: 3, fret: 2, duration: 0.5, interval: '4', noteName: 'A', technique: NoteTechnique.bendHalf),
      LickNote(string: 3, fret: 0, duration: 0.25, interval: 'b3', noteName: 'G'),
      LickNote(string: 4, fret: 2, duration: 0.5, interval: 'R', noteName: 'E', isTargetNote: true),
      LickNote(string: 5, fret: 2, duration: 0.25, interval: '5', noteName: 'B'),
      LickNote(string: 6, fret: 0, duration: 0.5, interval: 'R', noteName: 'E', isTargetNote: true),
    ],
  ),

  const ArtistLick(
    id: 'srv_texas_flood',
    artist: 'Stevie Ray Vaughan',
    title: 'Texas Flood 1.5-Step Overbend',
    difficulty: 'Advanced',
    defaultKey: 'G Minor',
    targetChord: 'G7',
    applicableDegrees: ['I', 'i'],
    scaleUsed: 'G Blues Scale',
    cagedForm: 'E Form',
    pentatonicBox: 1,
    description: '1번줄에서 기타 줄이 끊어질 듯 단3도(1.5음)를 끌어올려 울부짖는 절정의 블루스 벤딩 릭입니다.',
    theoryTips: '1번줄 6프렛 단3도(Bb)를 1.5음 벤딩하면 5도(D)에 도달하며, 블루노트(Db)를 통과할 때 엄청난 전율의 텐션을 생성합니다.',
    tags: ['1.5 Bend', 'Heavy Vibrato', 'Slow Blues', 'Overbend'],
    notes: [
      LickNote(string: 1, fret: 6, duration: 0.75, interval: 'b3', noteName: 'Bb', technique: NoteTechnique.bend1Half),
      LickNote(string: 1, fret: 3, duration: 0.25, interval: 'R', noteName: 'G', isTargetNote: true),
      LickNote(string: 2, fret: 6, duration: 0.25, interval: 'b7', noteName: 'F'),
      LickNote(string: 1, fret: 3, duration: 0.5, interval: 'R', noteName: 'G', technique: NoteTechnique.vibrato, isTargetNote: true),
    ],
  ),

  const ArtistLick(
    id: 'srv_scuttle_buttin',
    artist: 'Stevie Ray Vaughan',
    title: "Scuttle Buttin' Triple Rake Attack",
    difficulty: 'Advanced',
    defaultKey: 'E Minor',
    targetChord: 'E7',
    applicableDegrees: ['I'],
    scaleUsed: 'E Minor Pentatonic Box 1',
    cagedForm: 'E Form (12th fret)',
    pentatonicBox: 1,
    description: '뮤트된 줄들을 연속으로 긁어내리는 레이크(Rake) 뒤에 번개 같은 셋잇단음표로 박스를 휩쓰는 고난도 어택 릭입니다.',
    theoryTips: '레이크 타격음으로 리듬감을 극대화한 후, 1번줄 단3도(G) 벤딩에서 루트(E)와 5도(B)로 초고속 풀오프 하향합니다.',
    tags: ['Rake Attack', 'Fast Run', 'Triplets', 'Speed Blues'],
    notes: [
      LickNote(string: 3, fret: 12, duration: 0.125, interval: 'b3', noteName: 'G', technique: NoteTechnique.rake),
      LickNote(string: 2, fret: 12, duration: 0.125, interval: '5', noteName: 'B', technique: NoteTechnique.rake),
      LickNote(string: 1, fret: 15, duration: 0.5, interval: 'b3', noteName: 'G', technique: NoteTechnique.bendFull),
      LickNote(string: 1, fret: 12, duration: 0.25, interval: 'R', noteName: 'E', isTargetNote: true),
      LickNote(string: 2, fret: 15, duration: 0.25, interval: 'b7', noteName: 'D', technique: NoteTechnique.pull),
      LickNote(string: 2, fret: 12, duration: 0.25, interval: '5', noteName: 'B'),
      LickNote(string: 3, fret: 14, duration: 0.5, interval: '4', noteName: 'A', technique: NoteTechnique.vibrato),
    ],
  ),

  // ==========================================
  // 4. Gary Moore (게리 무어)
  // ==========================================
  const ArtistLick(
    id: 'moore_still_got_the_blues',
    artist: 'Gary Moore',
    title: 'Still Got The Blues Sustained Run',
    difficulty: 'Intermediate',
    defaultKey: 'A Minor',
    targetChord: 'Am',
    applicableDegrees: ['i', 'iv'],
    scaleUsed: 'A Natural Minor (Aeolian)',
    cagedForm: 'E Form',
    pentatonicBox: 1,
    description: '한국인이 가장 사랑하는 록 발라드 "Still Got The Blues"의 클라이맥스 상행 런과 폭발적인 서스테인 벤딩 릭입니다.',
    theoryTips: '루트(A)에서 시작해 b3, 4, 5, b7을 타고 올라간 뒤, 고음부 단3도(C)를 절규하듯 풀벤딩하여 4도(D)까지 끌어올리고 무한 서스테인 비브라토를 겁니다.',
    tags: ['Minor Ballad', 'Long Sustain', 'Aeolian', 'Fast Run'],
    notes: [
      LickNote(string: 4, fret: 7, duration: 0.25, interval: 'R', noteName: 'A', isTargetNote: true),
      LickNote(string: 3, fret: 5, duration: 0.25, interval: 'b3', noteName: 'C'),
      LickNote(string: 3, fret: 7, duration: 0.25, interval: '4', noteName: 'D'),
      LickNote(string: 2, fret: 5, duration: 0.25, interval: '5', noteName: 'E'),
      LickNote(string: 2, fret: 8, duration: 0.25, interval: 'b7', noteName: 'G'),
      LickNote(string: 1, fret: 5, duration: 0.25, interval: 'R', noteName: 'A', isTargetNote: true),
      LickNote(string: 1, fret: 8, duration: 1.0, interval: 'b3', noteName: 'C', technique: NoteTechnique.bendFull, isTargetNote: true),
    ],
  ),

  const ArtistLick(
    id: 'moore_parisienne',
    artist: 'Gary Moore',
    title: 'Parisienne Walkways Singing Cry',
    difficulty: 'Intermediate',
    defaultKey: 'A Minor',
    targetChord: 'Am',
    applicableDegrees: ['i', 'V'],
    scaleUsed: 'A Natural Minor (Singing Tone)',
    cagedForm: 'E Form (High)',
    pentatonicBox: 2,
    description: '끝없이 이어지는 서스테인과 비브라토로 가슴을 저미는 게리 무어의 시그니처 롱톤 릭입니다.',
    theoryTips: '1번줄 12프렛 완전5도(E)를 잡고 피드백에 가까운 와이드 비브라토를 유지한 뒤, 11도(D)와 b3도(C)를 거쳐 2번줄 루트(A)로 애절하게 종결합니다.',
    tags: ['Singing Vibrato', 'Minor Ballad', '5th to Root'],
    notes: [
      LickNote(string: 1, fret: 12, duration: 1.0, interval: '5', noteName: 'E', technique: NoteTechnique.vibrato, isTargetNote: true),
      LickNote(string: 1, fret: 10, duration: 0.25, interval: '4', noteName: 'D'),
      LickNote(string: 1, fret: 8, duration: 0.25, interval: 'b3', noteName: 'C'),
      LickNote(string: 2, fret: 10, duration: 0.75, interval: 'R', noteName: 'A', technique: NoteTechnique.vibrato, isTargetNote: true),
    ],
  ),

  const ArtistLick(
    id: 'moore_the_loner',
    artist: 'Gary Moore',
    title: 'The Loner Harmonic Minor Climax',
    difficulty: 'Advanced',
    defaultKey: 'D Minor',
    targetChord: 'A7 to Dm',
    applicableDegrees: ['V', 'i'],
    scaleUsed: 'D Harmonic Minor (C# Leading Tone)',
    cagedForm: 'A Form',
    pentatonicBox: 3,
    description: 'V도 도미넌트(A7)에서 i도(Dm)로 해결될 때, 하모닉 마이너의 장7도 이끄는음(C#)을 이용해 극적인 텐션을 폭발시키는 명연 릭입니다.',
    theoryTips: '1번줄 9프렛의 장7도(C#)를 벤딩하여 루트(D)를 찌른 뒤 비브라토로 해결하는 하모닉 마이너 스케일의 교과서적인 릭입니다.',
    tags: ['Harmonic Minor', 'Leading Tone', 'Resolution', 'Minor Rock'],
    notes: [
      LickNote(string: 3, fret: 9, duration: 0.25, interval: '9', noteName: 'E'),
      LickNote(string: 2, fret: 6, duration: 0.25, interval: 'b3', noteName: 'F'),
      LickNote(string: 2, fret: 10, duration: 0.25, interval: '5', noteName: 'A'),
      LickNote(string: 1, fret: 9, duration: 0.5, interval: '7', noteName: 'C#', technique: NoteTechnique.bendHalf),
      LickNote(string: 1, fret: 10, duration: 0.75, interval: 'R', noteName: 'D', technique: NoteTechnique.vibrato, isTargetNote: true),
    ],
  ),
];
